/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.io.File
import kotlin.io.path.absolutePathString
import kotlin.io.path.createTempFile
import kotlin.test.Test
import kotlin.test.assertEquals

class BackMeUpApplicationTest {

    @Test
    fun testStart_emptyArgs_resultError() {
        // arrange
        val sut = BackMeUpApplication()

        // act
        val result = sut.start(EMPTY_ARRAY)

        // assert
        assertEquals(BackMeUpResult.ERROR, result)
    }

    @Test
    fun testStart_emptyStringArgs_resultError() {
        // arrange
        val sut = BackMeUpApplication()

        // act
        val result = sut.start(ARRAY_OF_EMPTY_STRING)

        // assert
        assertEquals(BackMeUpResult.ERROR, result)
    }

    @Test
    fun testStart_invalidArgs_resultError() {
        // arrange
        val sut = BackMeUpApplication()

        // act
        val result = sut.start(INVALID_ARGS)

        // assert
        assertEquals(BackMeUpResult.ERROR, result)
    }

    @Test
    fun testStart_validArgs_resultSuccess() {
        // arrange
        val sut = BackMeUpApplication()

        // act
        val result = sut.start(VALID_PROCESS_VALID_PATH)

        // assert
        assertEquals(BackMeUpResult.SUCCESS, result)
    }

    @Test
    fun testStart_validProcessInvalidPath_resultError() {
        // arrange
        val sut = BackMeUpApplication()

        // act
        val result = sut.start(VALID_PROCESS_INVALID_PATH)

        // assert
        assertEquals(BackMeUpResult.ERROR, result)
    }

    companion object {
        val EMPTY_ARRAY = emptyArray<String>()
        val ARRAY_OF_EMPTY_STRING = arrayOf("", "")
        val INVALID_ARGS = arrayOf("abc", "def")
        val VALID_FILE = createTempFile("testDir")
        val INVALID_FILE = File("abcdef")
        val INIT_ARG = BackMeUpApplication.ARG_MARKER + BackMeUpApplication.ARG_INIT
        val VALID_PROCESS_INVALID_PATH = arrayOf(INIT_ARG, INVALID_FILE.absolutePath)
        val VALID_PROCESS_VALID_PATH = arrayOf(INIT_ARG, VALID_FILE.absolutePathString())
    }
}